name: mgba
summary: mGBA Game Boy Advance Emulator https://mgba.io/
description: |
  mGBA is an emulator for running Game Boy Advance games. It aims to be faster
  and more accurate than many existing Game Boy Advance emulators, as well as
  adding features that other emulators lack. It also supports Game Boy and
  Game Boy Color games..
adopt-info: mgba
base: core18

architectures:
  - build-on: i386
  - build-on: amd64

confinement: strict
grade: stable

apps:
  mgba-qt:
    environment:
      XLOCALEDIR: '$SNAP/usr/share/X11/locale'
      LOCPATH: '$SNAP/usr/lib/locale'
      XDG_CONFIG_HOME: '$HOME/.config'
      XKB_CONFIG_ROOT: '$SNAP/usr/share/X11/xkb'
      XDG_CONFIG_DIRS: '$SNAP/etc/xdg:$XDG_CONFIG_DIRS'
      XDG_DATA_HOME: '$SNAP/usr/share'
      DISABLE_WAYLAND: '1'
      LD_LIBRARY_PATH: '$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH'
    command: desktop-launch mgba-qt
    plugs:
      - x11
      - home
      - pulseaudio
      - opengl
      - joystick
  mgba:
    environment:
      XLOCALEDIR: '$SNAP/usr/share/X11/locale'
      LOCPATH: '$SNAP/usr/lib/locale'
      XDG_CONFIG_HOME: '$HOME/.config'
      XKB_CONFIG_ROOT: '$SNAP/usr/share/X11/xkb'
      XDG_CONFIG_DIRS: '$SNAP/etc/xdg:$XDG_CONFIG_DIRS'
      XDG_DATA_HOME: '$SNAP/usr/share'
      LD_LIBRARY_PATH: '$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH'
    command: mgba
    plugs:
      - x11
      - home
      - pulseaudio
      - opengl
      - joystick

parts:
  mgba:
    after: [desktop-qt5]
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag | grep ^0 | sort -V | tail -n 1)"
      last_released_tag="$(snap info mgba | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags)"
    configflags:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
    source: https://github.com/mgba-emu/mgba.git
    build-packages:
      - libedit-dev
      - libavcodec-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libminizip-dev
      - libpng-dev
      - libzip-dev
      - libmagickwand-dev
      - libepoxy-dev
      - libsqlite3-dev
      - libsdl2-dev
      - libswscale-dev
      - qtdeclarative5-dev
      - qtmultimedia5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libpixman-1-dev
      - libqt5opengl5-dev
      - qtbase5-dev
      - zlib1g-dev
    stage-packages:
      - librtmp1
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libepoxy0
      - libzvbi0
      - libzip4
      - libxvidcore4
      - libwebp6
      - libwavpack1
      - libvpx5
      - libtwolame0
      - libtheora0
      - libssh-gcrypt-4
      - libspeex1
      - libsoxr0
      - libsndio6.1
      - libsnappy1v5
      - libshine3
      - libopus0
      - libnuma1
      - libmp3lame0
      - libmodplug1
      - libltdl7
      - liblqr-1-0
      - libgsm1
      - libgomp1
      - libgme0
      - libfftw3-double3
      - libcrystalhd3
      - libxss1
      - libsdl2-2.0-0
      - libx264-152
      - libx265-146
      - libva2
      - libswscale4
      - libswresample2
      - libmagickwand-6.q16-3
      - libopenjp2-7
      - libbluray2
      - libavutil55
      - libavresample3
      - libavformat57
      - libmagickcore-6.q16-3

  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5
    - try:
      - appmenu-qt5
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
